variable "vpc_id" {}
variable "secure_subnet_az1_id" {}
variable "secure_subnet_az2_id" {}
variable "alb_security_group_id" {}
variable "ec2_security_group_id" {}
variable "az1" {}
variable "az2" {}
variable "identifier" {}
variable "username" {}
variable "password" {}
variable "db_name" {}