variable "ami" {}
variable "project_name" {}
variable "rds_db_endpoint" {}
variable "private_subnet_az1_id" {}
variable "private_subnet_az2_id" {}
variable "application_load_balancer" {}
variable "alb_target_group_arn" {}
variable "alb_security_group_id" {}
variable "ec2_security_group_id" {}
variable "iam_ec2_instance_profile" {}